import { page_imgBundle } from "./image";

export const projects = [
    {
      id: 1,
      title: "RENEWAL PROJECT",
      src: `${page_imgBundle[1].src}` ,
      explain: "대한민국의 치킨 브랜드인 지코바의 홈페이지를 리뉴얼 했습니다. ",
      TechStack: '#HTML',
      TechStack: '#CSS',
      TechStack: '#JAVASCRIPT',
      TechStack: '#NODE.JS',
      TechStack: '#EXPRESS.JS',
      Period: '2024.03.26 ~ 2024.04.22',
      page_link: "/",
      github_link: "/",
    },
    {
      id: 2,
      title: "고궁의 밤",
      src: `${page_imgBundle[2].src}` ,
      explain: "고궁에서 개최되는 야간 행사를 홍보하고 안내하는 사이트입니다. 처음으로 팀원들과 함께 작업한 자체 제작 사이트입니다.",
      TechStack: '#CSS',
      TechStack: '#JAVASCRPT',
      TechStack: '#REACT',
      TechStack: '#VITE',
      TechStack: '#SWIPER',
      TechStack: '#THREE.JS',
      TechStack: '#REST API',
      TechStack: '#AOS',
      Period: '2024.05.16 ~ 2024.06.18',
      page_link: "https://juramii.github.io/Team_Period/",
      github_link: "https://github.com/JURAMII/Team_Period",
    },
    {
      id: 3,
      title: "EZDOMATH",
      src:  `${page_imgBundle[3].src}`,
      explain: "초등학생을 위한 수학 교육 사이트입니다. 3D scene을 이용한 입체적은 문제풀이와 로컬 스토리지를 이용한 자체 로그인 및 회원가입 기능을 가지고 있습니다.",
      TechStack: '#CSS',
      TechStack: '#JAVASCRPT',
      TechStack: '#REACT',
      TechStack: '#VITE',
      TechStack: '#SWIPER',
      TechStack: '#THREE.JS',
      TechStack: '#REST API',
      TechStack: '#GSAP',
      Period: '2024.07.08 ~ 2024.08.06',
      page_link: "https://thesandfox.github.io/ezdomath/",
      github_link: "https://github.com/TheSandfox/ezdomath",
    },
    {
      id: 4,
      title: "PORTFOLIO WEB SITE",
      src:  `${page_imgBundle[8].src}`,
      explain: "현재 보고 계신 포트폴리오 웹 사이트 입니다.",
      TechStack: '#CSS',
      TechStack: '#JAVASCRPT',
      TechStack: '#REACT',
      TechStack: '#SWIPER',
      TechStack: '#THREE.JS',
      TechStack: '#GSAP',
      Period: '2024.06.19 ~ 2024.07.08 + Continuously updating',
      page_link: "/",
      github_link: "https://github.com/Shikaboo/shinoboo_portfolio",
    },
  ];

  export const clones = [
    {
      id: 1,
      title: "Domino Pizza",
      src:  `${page_imgBundle[0].src}`,
      description: "도미노 피자 메인 페이지를 클로닝 했습니다. 미디어쿼리를 통한 반응형 작업과 JS를 통한 간단한 동적 기능을 추가했습니다.",
      page_link: "https://shikaboo.github.io/cloning-domino/",
      github_link: "https://github.com/Shikaboo/cloning-domino",
    },
    {
      id: 2,
      title: "Lotte Bizcar",
      src:  `${page_imgBundle[5].src}`,
      description: "롯데 비즈카 메인 페이지를 클로닝 했습니다. 미디어쿼리를 통한 반응형 작업 및 스와이퍼 cdn을 연결하여 슬라이드 기능과 JS를 통해 간단한 버튼 클릭 메뉴 기능을 구현했습니다.",
      page_link: "https://shikaboo.github.io/cloning-bizcar/",
      github_link: "https://github.com/Shikaboo/cloning-bizcar",
    },
    {
      id: 3,
      title: "국립공주박물관",
      src:  `${page_imgBundle[4].src}`,
      description: "국립 공주 박물관 메인 페이지를 클로닝 했습니다. position을 이용해 사이트가 꾸며져 있었기에 최대한 position을 사용하지 않는 선에서 메인 페이지를 따라해보려 노력했습니다, 앞선 클로닝 사이트와 마찬가지로 간단한 반응형 작업도 진행했습니다.",
      page_link: "https://museum.go.kr",
      github_link: "https://github.com/museum",
    },
    {
      id: 4,
      title: "KT&G 장학재단",
      src:  `${page_imgBundle[6].src}`,
      description: "KT&G 장학재단의 웹 사이트를 클로닝 했습니다. 웹 사이트 내의 position과 특정 컨텐츠를 @keyframes를 통해 움직이는 법에 대해 알게됐습니다.",
      page_link: "https://shikaboo.github.io/cloning_ktng/",
      github_link: "https://github.com/Shikaboo/cloning_ktng",
    },
    {
      id: 5,
      title: "SOCAR",
      src:  `${page_imgBundle[4].src}`,
      description: "SOCAR의 메인 페이지를 클로닝 했습니다. 리액트를 처음 배울 당시에 리액트 문법 및 컴포넌트 사용을 숙달하기 위해 클로닝을 진행했습니다.",
      page_link: "https://socar.com",
      github_link: "https://github.com/socar",
    },
  ];

  export const toys = [
    {
      id : 1,
      title: "Front-end dictionary",
      name: "프론트엔드 사전",
      src: `${page_imgBundle[7].src}`,
      description: "React를 통해 24년 상반기동안 배웠던 프론트엔드 개발에 관한 내용을 간략하게 정리해놓은 사전입니다. 이용자가 직접 사전에 내용을 추가할 수도 있습니다.",
      page_link: "https://shikaboo.github.io/dictionary/",
      github_link: "https://github.com/Shikaboo/dictionary",
    },
    {
      id : 2,
      title: "My Second Toy Project",
      name: "준비중입니다.",
      src: `${page_imgBundle[4].src}`,
      description: "해당 토이 프로젝트에 대한 간략한 설명 을 할 예정입니다 -----(만든 이유, 기능, 사용 기술 등을서술)-----",
      page_link: "/",
      github_link: "/",
    },
  ]
  